-- Add additional fields to products table for CSV import
ALTER TABLE PRODUCTS
    ADD COLUMN IF NOT EXISTS EXTERNAL_ID TEXT, ADD COLUMN IF NOT EXISTS PRODUCT_TYPE TEXT, ADD COLUMN IF NOT EXISTS GTIN TEXT, ADD COLUMN IF NOT EXISTS UPC TEXT, ADD COLUMN IF NOT EXISTS EAN TEXT, ADD COLUMN IF NOT EXISTS ISBN TEXT, ADD COLUMN IF NOT EXISTS SHORT_DESCRIPTION TEXT, ADD COLUMN IF NOT EXISTS CATEGORIES TEXT[], ADD COLUMN IF NOT EXISTS TAGS TEXT[];

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_EXTERNAL_ID ON PRODUCTS(EXTERNAL_ID);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_PRODUCT_TYPE ON PRODUCTS(PRODUCT_TYPE);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_GTIN ON PRODUCTS(GTIN);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_UPC ON PRODUCTS(UPC);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_EAN ON PRODUCTS(EAN);

CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_ISBN ON PRODUCTS(ISBN);

-- Add comments for documentation
COMMENT ON COLUMN PRODUCTS.EXTERNAL_ID IS 'External ID from CSV import';
COMMENT ON COLUMN PRODUCTS.PRODUCT_TYPE IS 'Product type/category from CSV import';
COMMENT ON COLUMN PRODUCTS.GTIN IS 'Global Trade Item Number';
COMMENT ON COLUMN PRODUCTS.UPC IS 'Universal Product Code';
COMMENT ON COLUMN PRODUCTS.EAN IS 'European Article Number';
COMMENT ON COLUMN PRODUCTS.ISBN IS 'International Standard Book Number';
COMMENT ON COLUMN PRODUCTS.SHORT_DESCRIPTION IS 'Short description from CSV import';
COMMENT ON COLUMN PRODUCTS.CATEGORIES IS 'Array of product categories';
COMMENT ON COLUMN PRODUCTS.TAGS IS 'Array of product tags';